---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lowlevel-mcp
  namespace: lowlevel-mcp
  labels:
    app: lowlevel-mcp
spec:
  selector:
    matchLabels:
      app: lowlevel-mcp
  template:
    metadata:
      labels:
        app: lowlevel-mcp
    spec:
      serviceAccountName: lowlevel-sa      
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: lowlevel-daemonset
        image: quay.io/REPLACE_WITH_YOUR_USERNAME/lowlevel-mcp
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 9028
          name: mcp-port
          protocol: TCP
      hostPID: true
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lowlevelmcp-service
spec:
  selector:
    app: lowlevel-mcp
  clusterIP: None
  type: ClusterIP
  ports:
    - name: mcp
      protocol: TCP
      port: 9028
      targetPort: 9028

